version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: frknmydn  
      POSTGRES_PASSWORD: veryberrysecret
    ports:
      - "5432:5432"
    volumes:
      - C:\docker-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: furkanmeydann@gmail.com
      PGADMIN_DEFAULT_PASSWORD: veryberrysecret
    ports:
      - "5050:80"
    depends_on:
      - postgres
